# Generated by Django 4.2.2 on 2023-06-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tournament_organizer', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('charity', models.BooleanField()),
                ('promoted', models.BooleanField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
