# Generated by Django 4.2.2 on 2023-06-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='charity',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
