# Generated by Django 4.2.2 on 2023-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category_alter_event_charity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=1000)),
                ('calendar_link', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
